### ISSUE TITLE
Voxelsniper /b over not working for me

### ISSUE THREAD

**Issue by WeltensiedlerDE** [IntellectualSites/FastAsyncVoxelSniper-Legacy#3]
# Bug report for FastAsyncWorldEdit 1.13.x
Hello, in your doscord support channel you said me, I have to open a ticket. Here it is. Thank you for your help.

**Debug paste link**:
https://incendo.org/paste/view/5b742c301c9f4f6bb05a12ea532cc22b
https://pastebin.com/Eyd2yvrP

**Description of the problem:**
I want to cover a stone mountain with 2 layers grass using the commands /b over d2, /b 5 and /v 2 (/v grass_block makes nothing too)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Duplicate of #2
