### ISSUE TITLE
have Problem with FAVS

### ISSUE THREAD

**Issue by KyleCro** [IntellectualSites/FastAsyncVoxelSniper-Legacy#9]
When i try to /v 1 i get this error in console
java.lang.IllegalAccessError: tried to access method com.sk89q.worldedit.function.mask.AbstractExtentMask.<init>(Lcom/sk89q/worldedit/extent/Extent;)V from class com.thevoxelbox.voxelsniper.util.VoxelList 

and in game it says that the error has send to console i hope you can help

**Comment by NotMyFault** [comment]
Do not delete the template.
